/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "namenode.h"


void
namenode_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char * openfile_1_arg;
	char * *result_2;
	char * getblocklocations_1_arg;
	char * *result_3;
	char * assignblock_1_arg;
	char * *result_4;
	char * closefile_1_arg;
	char * *result_5;
	char * list_1_arg;
	char * *result_6;
	char * sendblockreport_1_arg;
	char * *result_7;
	char * sendheartbeat_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NAMENODE, NN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = openfile_1(&openfile_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = getblocklocations_1(&getblocklocations_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = assignblock_1(&assignblock_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = closefile_1(&closefile_1_arg, clnt);
	if (result_4 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = list_1(&list_1_arg, clnt);
	if (result_5 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = sendblockreport_1(&sendblockreport_1_arg, clnt);
	if (result_6 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = sendheartbeat_1(&sendheartbeat_1_arg, clnt);
	if (result_7 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	namenode_1 (host);
exit (0);
}
