/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "datanode.h"


void
datanode_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char *result_1;
	char * readblock_1_arg;
	enum clnt_stat retval_2;
	char *result_2;
	char * writeblock_1_arg;
	enum clnt_stat retval_3;
	char *result_3;
	char * sendblockreportmsg_1_arg;
	enum clnt_stat retval_4;
	char *result_4;
	char * sendheartbeatmsg_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DATANODE, DN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = readblock_1(&readblock_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = writeblock_1(&writeblock_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = sendblockreportmsg_1(&sendblockreportmsg_1_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = sendheartbeatmsg_1(&sendheartbeatmsg_1_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	datanode_1 (host);
exit (0);
}
