/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "datanode.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
readblock_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, readBlock,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
writeblock_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, writeBlock,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sendblockreportmsg_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, sendBlockReportMsg,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sendheartbeatmsg_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, sendHeartBeatMsg,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}
