/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "namenode.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
openfile_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, openFile,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getblocklocations_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, getBlockLocations,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
assignblock_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, assignBlock,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
closefile_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, closeFile,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
list_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, list,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sendblockreport_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, sendBlockReport,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sendheartbeat_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, sendHeartBeat,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}
