/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "namenode.h"


void
namenode_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char *result_1;
	char * openfile_1_arg;
	enum clnt_stat retval_2;
	char *result_2;
	char * getblocklocations_1_arg;
	enum clnt_stat retval_3;
	char *result_3;
	char * assignblock_1_arg;
	enum clnt_stat retval_4;
	char *result_4;
	char * closefile_1_arg;
	enum clnt_stat retval_5;
	char *result_5;
	char * list_1_arg;
	enum clnt_stat retval_6;
	char *result_6;
	char * sendblockreport_1_arg;
	enum clnt_stat retval_7;
	char *result_7;
	char * sendheartbeat_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NAMENODE, NN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = openfile_1(&openfile_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = getblocklocations_1(&getblocklocations_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = assignblock_1(&assignblock_1_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = closefile_1(&closefile_1_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = list_1(&list_1_arg, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = sendblockreport_1(&sendblockreport_1_arg, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = sendheartbeat_1(&sendheartbeat_1_arg, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	namenode_1 (host);
exit (0);
}
